### ISSUE TITLE
Clicking on "כל הארץ"  sends me to my locality 

### ISSUE THREAD

**Issue by Suberri** [hasadna/open-shot#218]

**Comment by gl1000007** [comment]
duplicate: #152

**Comment by daonb** [comment]
I think it's a feature...

**Comment by gl1000007** [comment]
@daonb I hope you're joking. Please read #152. All of it.

**Comment by lotan1** [comment]
as well as clicking our logo will sends you to your locality

**Comment by daonb** [comment]
Following Monday meeting it was agreed that as long as we don't have a nation-wide view, this works fine.

**Comment by danielhers** [comment]
What I understood from the last meeting is that the default page should be the user's locality (and it is reached by clicking the logo). However, I think the "כל הארץ" link is a slightly different issue: since it does not send you to a nation-wide view, it is misleading. Perhaps this link should just be hidden for now.

**Comment by daonb** [comment]
#252
