### ISSUE TITLE
add support option to questions on main locality list

### ISSUE THREAD

**Issue by polinas123** [hasadna/open-shot#255]
when displaying locality page (e.g http://localshot.org.il/%D7%99%D7%A8%D7%95%D7%A9%D7%9C%D7%99%D7%9D-2/qna/) users need the option to support questions from the list (without clicking on specific question)
so that in short time user can support multiple questions

**Comment by daonb** [comment]
Question is, can it be too easy to support a question? If we make the
interface as easy as you suggest, aren't we risking having all the users
support all the questions?

**Comment by lotan1** [comment]
maybe we`ll let them over support at the begining, then if it`ll be too much we`ll change it

**Comment by polinas123** [comment]
I see what you're saying benny, but I think right now we are risking no
support at all.
It may change when questions will have answers so people will have an
insentive to click them. But yet again, than we might get
supported-answered linkage, while the interesting questions left untouched.
So I tend to agree with Lotan

**Comment by gl1000007** [comment]
copied from #206 
![support question on question list](https://f.cloud.github.com/assets/5072931/1197700/85b32f88-24e2-11e3-9fec-283e8159f324.png)

**Comment by gl1000007** [comment]
[new wireframe](http://www.google.com/url?q=https%3A%2F%2Fdocs.google.com%2Ffile%2Fd%2F0B3yaQaorsX55ZVJRd0l3UWV0VjA%2Fedit%3Fusp%3Dsharing) in order to provide context, look at the bottom.
and a [detailed](https://docs.google.com/document/d/13nz0ByXhC7KsE_S8QklabbTWCHMlopPkfhnKHzcia5I/edit?pli=1#bookmark=id.tgr4lxrwsuen) document in Google drive, but you don't need to read it. This is the document that the wireframe came from.

**Comment by danielhers** [comment]
Working on it.
