### ISSUE TITLE
add candidate first displays list of users in locality without the candidates

### ISSUE THREAD

**Issue by polinas123** [hasadna/open-shot#295]
if you create a list and then add candidate, the users list to choose from is the locality users list
clicking יצירה without choosing anything will open the list to all users in the whole system (including candidates).
much better to first show only candidates listed in the relevant locality
it will also prevent local editors adding themselves as candidates by mistake

**Comment by tbrisker** [comment]
if a user is already listed as a candidate there is no point in listing him again - the editor interface is intended to mark users as candidates. once an editor adds a user as a candidate that user is set as is_candidate automatically. if you mark them as candidates in the admin instead of adding them to a list it will lead to bugs such as this and as their user profile causing problems - no user should be set as candidate if they are not added to a candidate list. if you want I can also remove the editors from the list of possible users.
