### ISSUE TITLE
Change calculation method for response rate in a locality

### ISSUE THREAD

**Issue by gl1000007** [hasadna/open-shot#396]
Existing method: % of (sum of questions \* sum of candidates)
That leads to:
- Very low rates, even in active cities like [Jerusalem](http://localshot.org.il/55/qna/).
- Getting 100% requires every candidate to answer every question. That includes **every candidate in every list**, and it's a lot. It will mess up the question page, and is generally an unreachable goal.

New calculation method (proposal):
100% = at least one answer from every list, to every question.
For that matter, a "Single List" (רשימת יחיד) is also a list.
That single answer can be written by the candidate for mayor, or by someone on their list.

what do you think?

**Comment by tbrisker** [comment]
too complicated. change to simple answer count.

**Comment by gl1000007** [comment]
Can't you run a query for list IDs that linked to a certain question ID? That's all there is to it, assuming that every candidate is linked to a list.
If still complicated, please explain why, including any relevant constraints.

**Comment by tbrisker** [comment]
it's complicated because it's a number that has no intuitive meaning to the user - they know what an answer count is, they don't know what a response rate % means.
Also the calculation is very heavy on the db - checking every question for entity, then every question all answers and who answered etc, which is calculated every time a page is loaded...

**Comment by gl1000007** [comment]
Simple answer count.

**Comment by lotan1** [comment]
כמו לגבי תצוגת מועמדים רשומים
להבנתי, אם לא ניתן לשינוי מהיר,
עדיף למחוק זמנית מאשר להציג כך
